import React, { useState, useEffect } from 'react';
import { ShieldCheck, Target, TrendingUp, Award, Clock, ArrowRight } from 'lucide-react';
import { Skeleton } from '../components/ui/Skeleton';
import { getBadgeClass } from '../lib/badge';

import apiClient from '../api/client';

export const AccuracyPage: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<any>({ overall_accuracy: 0, total_signals: 0, avg_gain: 0, win_rate_30d: 0 });
  const [leaderboard, setLeaderboard] = useState<any[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [statsRes, leaderboardRes] = await Promise.all([
          apiClient.get('/accuracy/'),
          apiClient.get('/accuracy/leaderboard')
        ]);
        setStats(statsRes.data);
        setLeaderboard(leaderboardRes.data);
      } catch (error) {
        console.error("Failed to fetch accuracy stats", error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  if (loading) return <div className="p-8"><Skeleton className="h-96 w-full" /></div>;

  return (
    <div className="min-h-screen bg-black text-white p-4 md:p-8 animate-in fade-in duration-700">
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="mb-12">
          <div className="flex items-center gap-2 text-zinc-500 font-mono text-sm mb-4 uppercase tracking-widest">
            <ShieldCheck size={16} className="text-green-500" />
            <span>Institutional Transparency Dashboard</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tighter italic mb-6">
            SIGNAL ACCURACY
          </h1>
          <p className="text-zinc-400 text-lg max-w-3xl leading-relaxed">
            We track every single BUY, SELL, and HOLD recommendation generated by our 7-agent pipeline. 
            All data is verified against real market close prices with zero retro-adjustments.
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-12">
          {[
            { label: "Overall Accuracy", value: `${stats.overall_accuracy ?? 0}%`, icon: Target, color: "text-green-500" },
            { label: "Total Signals", value: stats.total_signals ?? 0, icon: Clock, color: "text-blue-500" },
            { label: "Avg. ROI / Signal", value: `${(stats.avg_gain ?? 0) >= 0 ? '+' : ''}${stats.avg_gain ?? 0}%`, icon: TrendingUp, color: "text-purple-500" },
            { label: "30D Win Rate", value: `${stats.win_rate_30d ?? 0}%`, icon: Award, color: "text-yellow-500" }
          ].map((item, i) => (
            <div key={i} className="bg-zinc-950 border border-zinc-900 p-6 rounded-2xl">
              <item.icon size={20} className={`${item.color} mb-4`} />
              <div className="text-zinc-500 text-xs font-bold uppercase tracking-widest mb-1">{item.label}</div>
              <div className="text-3xl font-black tracking-tighter">{item.value}</div>
            </div>
          ))}
        </div>

        {/* Accountability Table */}
        <div className="bg-zinc-950 border border-zinc-900 rounded-3xl overflow-hidden">
          <div className="p-8 border-b border-zinc-900 flex items-center justify-between">
            <h2 className="text-2xl font-bold tracking-tight">Leaderboard by Symbol</h2>
            <button className="text-sm font-bold text-zinc-500 hover:text-white flex items-center gap-2 transition-colors">
              View All <ArrowRight size={16} />
            </button>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-zinc-900/50 text-zinc-500 uppercase text-[10px] font-bold tracking-widest">
                  <th className="px-8 py-4">Ticker</th>
                  <th className="px-8 py-4">Market</th>
                  <th className="px-8 py-4">Win Rate</th>
                  <th className="px-8 py-4">Avg. Perf</th>
                  <th className="px-8 py-4">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-900">
                {leaderboard.map((row, i) => (
                  <tr key={i} className="group hover:bg-zinc-900/30 transition-colors cursor-pointer">
                    <td className="px-8 py-6 font-black italic text-xl tracking-tighter">{row.symbol}</td>
                    <td className="px-8 py-6 text-zinc-400 font-mono text-sm">{row.market}</td>
                    <td className="px-8 py-6">
                      <div className="flex items-center gap-3">
                        <span className="font-bold">{row.win_rate}%</span>
                        <div className="w-24 bg-zinc-900 h-1.5 rounded-full overflow-hidden">
                          <div 
                            className="bg-green-500 h-full transition-all duration-1000" 
                            style={{ width: `${row.win_rate}%` }} 
                          />
                        </div>
                      </div>
                    </td>
                    <td className={`px-8 py-6 font-bold ${(row.avg_return ?? 0) >= 0 ? 'text-green-500' : 'text-red-500'}`}>
                      {(row.avg_return ?? 0) >= 0 ? '+' : ''}{row.avg_return ?? 0}%
                    </td>
                    <td className="px-8 py-6">
                      <span className={`px-3 py-1 text-[10px] font-bold rounded-full uppercase tracking-tighter border ${getBadgeClass(row.verification_state || 'verified')}`}>
                        {row.verification_state || 'verified'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Disclaimer Footer */}
        <div className="mt-12 p-8 bg-zinc-900/30 border border-zinc-800 rounded-2xl text-zinc-500 text-sm italic">
          Disclaimer: Historical performance does not guarantee future results. Accuracy is calculated based on the signal price vs the market close price 5 trading days after the signal was issued. Market data for US stocks is provided via yfinance and for NGX via direct exchange scraping.
        </div>
      </div>
    </div>
  );
};
